import { Inter } from "next/font/google";
import "./globals.sass";
import "@/app/js/app"
import { SpeedInsights } from "@vercel/speed-insights/next"
import { Analytics } from '@vercel/analytics/react';
import { GetUserInfoForServer } from "./AuthControllers/GetDataController";
import { Providers } from '@/app/context/contextProvider';
import { Loading } from '@/app/components/loading';


import StartJS from "./components/startJS";

const inter = Inter({ subsets: ["latin"] });
export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
    console.log('старт')
    const user = await GetUserInfoForServer();
    console.log('финиш')
    console.log('user:', user)
    return (
        <html lang="uk">
            <head>
                <meta charSet="UTF-8" />
            </head>
            <body>
                <Loading />
                <Providers user={user[0] ? user[1] : undefined}>
                    <div className="wrapper">
                        {children}
                    </div>
                    <SpeedInsights />
                    <Analytics />
                </Providers>
                <StartJS />
            </body>
        </html>
    );
}
