import { Inter } from "next/font/google";
import "./globals.sass";

import './js/app.js'


const inter = Inter({ subsets: ["latin"] });
export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="uk">
            <head>
                <meta charSet="UTF-8" />
            </head>
            <body>
                <div className="wrapper">
                    {children}
                </div>
            </body>
        </html>
    );
}
